name: Terraform Remote State Action
description: Fetches remote state from a Terraform Cloud Workspace
inputs:
  workspace:
    description: Workspace name
    required: true
  organization:
    description: Organization
    required: true
  address:
    required: false
    description: Terraform Cloud address
    default: https://app.terraform.io
  token:
    required: true
    description: Terraform cloud token
  target: 
    required: false
    description: The output key to target
  sensitive:
    description: Whether to mask the fetched remote state
    required: false
    default: "true"
  debug:
    description: Whether to log debugging information
    required: false
    default: "false"
outputs:
  output:
    description: JSON workspace outputs
runs:
  using: docker
  image: Dockerfile